
module.exports = {
	away:    require('./away'),
	invite:  require('./invite'),
	join:    require('./join'),
	kick:    require('./kick'),
	mode:    require('./mode'),
	bans:    require('./bans'),
	motd:    require('./motd'),
	names:   require('./names'),
	nick:    require('./nick'),
	notice:  require('./notice'),
	part:    require('./part'),
	pong:    require('./pong'),
	privmsg: require('./privmsg'),
	quit:    require('./quit'),
	topic:   require('./topic'),
	welcome: require('./welcome'),
	whois:   require('./whois'),
};
